name: "Build submission in Ubuntu"

on: [repository_dispatch]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu
            cc: gcc-10
            cxx: g++-10
            arch: x64

    runs-on: ${{ matrix.config.os }}-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ secrets.REPO }}
        ssh-key: ${{ secrets.BOT_SSH_KEY }}
        ref: ${{ github.event.client_payload.ref }}
    
    - run: echo ${{ github.event.client_payload.sha }}

    - name: install compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10

    - name: Prepare compiler env
      run: |
        echo "::set-env name=CC::${{ matrix.config.cc }}"
        echo "::set-env name=CXX::${{ matrix.config.cxx }}"

    - name: build
      run: |
        ./build.sh

    - name: notification
      if: cancelled() == false
      uses: variar/action-telegram@v1.3
      with:
        botToken: ${{ secrets.TG_TOKEN }}
        chatId: ${{ secrets.TG_CHANNEL }}
        commitHash: ${{ github.event.client_payload.sha }}
        commitActor: ${{ github.event.client_payload.actor }}
        comment: org
        jobStatus: ${{ job.status }}
        skipSuccess: false
